/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login With Google
         * @description Inicia sesión o registra al usuario con un id_token emitido por Google OAuth.
         *     Valida firma, aud, iss, exp y email_verified.
         *     Fija la cookie de sesión firmada 'facturia_session'.
         */
        post: operations["login_with_google_v1_auth_google_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Cierra la sesión y borra la cookie HttpOnly.
         */
        post: operations["logout_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Me
         * @description Devuelve la información del usuario actual, sus empresas asociadas
         *     y su rol dentro de cada una.
         */
        get: operations["get_me_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tenants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List User Tenants
         * @description Lista todos los tenants a los que pertenece el usuario.
         */
        get: operations["list_user_tenants_v1_tenants_get"];
        put?: never;
        /**
         * Create Tenant
         * @description Crea un nuevo tenant y asigna al usuario actual como 'owner'.
         */
        post: operations["create_tenant_v1_tenants_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/team": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Team
         * @description Lista a todos los miembros del equipo de la empresa activa.
         *     La consulta se ejecuta estrictamente dentro de tenant_session() para cumplir con RLS.
         */
        get: operations["list_team_v1_team_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/team/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Invite Team Member
         * @description Invita o agrega a un miembro al equipo.
         *     Regla: Nadie puede asignar un rol superior al suyo.
         */
        post: operations["invite_team_member_v1_team_invitations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/team/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Member Role
         * @description Actualiza el rol de un miembro del equipo.
         *     Reglas:
         *     1. Nadie puede asignar un rol superior al suyo.
         *     2. Nadie puede modificar a un usuario con un rol superior al suyo.
         *     3. Un owner no puede degradarse a sí mismo si es el único owner.
         */
        patch: operations["update_member_role_v1_team__user_id__patch"];
        trace?: never;
    };
    "/v1/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Tickets
         * @description Lista tickets con filtros por estado y comercio, y paginación por cursor.
         */
        get: operations["list_tickets_v1_tickets_get"];
        put?: never;
        /**
         * Upload Ticket
         * @description Sube un ticket para procesamiento asíncrono:
         *     1. Valida el tipo por magic bytes (JPEG, PNG, HEIC, WebP, PDF) y tamaño (máx 10 MB).
         *     2. Sube en streaming a S3/MinIO sin cargar el archivo completo en memoria.
         *     3. Registra el ticket en estado 'recibido' dentro de tenant_session.
         *     4. Encola la tarea de extracción en ARQ con tenant_id explícito y responde 202.
         */
        post: operations["upload_ticket_v1_tickets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tickets/{ticket_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Ticket
         * @description Consulta el detalle de un ticket específico.
         */
        get: operations["get_ticket_v1_tickets__ticket_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Ticket
         * @description Elimina un ticket del tenant:
         *     - Borra la imagen de S3/MinIO si no ha sido borrada aún.
         *     - Borra los eventos asociados y el ticket de la base de datos (con RLS activo).
         */
        delete: operations["delete_ticket_v1_tickets__ticket_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tickets/{ticket_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Ticket Events
         * @description Server-Sent Events (SSE) de los ticket_events (Trampa 2 evitada):
         *     - NO mantiene transacciones abiertas: cada ciclo abre su propia tenant_session() corta.
         *     - Emite keep-alive ': keep-alive\n\n' cada 15 segundos.
         *     - Cierra el stream automáticamente al alcanzar un estado final.
         */
        get: operations["stream_ticket_events_v1_tickets__ticket_id__stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tickets/{ticket_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Retry Ticket
         * @description Reintenta el proceso de facturación de un ticket previamente RECHAZADO:
         *     - Solo permitido si el estado actual es 'rechazado'.
         *     - Límite estricto de máximo 3 intentos.
         *     - Transiciona a 'encolado' y encola de nuevo en ARQ.
         */
        post: operations["retry_ticket_v1_tickets__ticket_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tickets/{ticket_id}/cfdi": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download Cfdi Bundle
         * @description Descarga efímera del CFDI 4.0 (ZIP con PDF y XML):
         *     - Solo disponible si el portal entregó archivos directos (entrega='descarga').
         *     - Recupera el archivo de Redis descifrado con la llave del tenant.
         *     - Máximo 5 descargas dentro de los 30 minutos; al expirar o superar el límite devuelve 404 cfdi_expirado.
         */
        get: operations["download_cfdi_bundle_v1_tickets__ticket_id__cfdi_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Endpoint de salud del sistema.
         *     Verifica la conectividad con PostgreSQL usando el rol de aplicación.
         */
        get: operations["health_check_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_upload_ticket_v1_tickets_post */
        Body_upload_ticket_v1_tickets_post: {
            /** File */
            file: string;
            /** Merchant Slug */
            merchant_slug?: string | null;
            /** Fiscal Profile Id */
            fiscal_profile_id?: string | null;
        };
        /** CreateTenantRequest */
        CreateTenantRequest: {
            /** Nombre */
            nombre: string;
            /** Slug */
            slug?: string | null;
        };
        /** GoogleAuthRequest */
        GoogleAuthRequest: {
            /** Id Token */
            id_token: string;
        };
        /** GoogleAuthResponse */
        GoogleAuthResponse: {
            /** User Id */
            user_id: string;
            /** Email */
            email: string;
            /** Nombre */
            nombre: string;
            /** Avatar Url */
            avatar_url?: string | null;
            /** Created Tenant Id */
            created_tenant_id?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InviteMemberRequest */
        InviteMemberRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Nombre */
            nombre?: string | null;
            rol: components["schemas"]["MembershipRole"];
        };
        /** MeResponse */
        MeResponse: {
            /** Id */
            id: string;
            /** Email */
            email: string;
            /** Nombre */
            nombre: string;
            /** Avatar Url */
            avatar_url?: string | null;
            /** Tenants */
            tenants: components["schemas"]["UserTenantResponse"][];
        };
        /**
         * MembershipRole
         * @enum {string}
         */
        MembershipRole: "owner" | "admin" | "uploader" | "viewer";
        /** PaginatedTicketsResponse */
        PaginatedTicketsResponse: {
            /** Items */
            items: components["schemas"]["TicketResponse"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** TeamMemberResponse */
        TeamMemberResponse: {
            /** User Id */
            user_id: string;
            /** Nombre */
            nombre: string;
            /** Email */
            email: string;
            /** Rol */
            rol: string;
            /** Avatar Url */
            avatar_url?: string | null;
        };
        /** TenantResponse */
        TenantResponse: {
            /** Id */
            id: string;
            /** Nombre */
            nombre: string;
            /** Slug */
            slug: string;
            /** Plan */
            plan: string;
            /** Rol */
            rol: string;
        };
        /**
         * TicketEstado
         * @enum {string}
         */
        TicketEstado: "recibido" | "extrayendo" | "extraido" | "encolado" | "facturando" | "espera_humano" | "facturado" | "rechazado" | "cancelado";
        /** TicketResponse */
        TicketResponse: {
            /** Id */
            id: string;
            /** Tenant Id */
            tenant_id: string;
            /** Estado */
            estado: string;
            /**
             * Intentos
             * @default 0
             */
            intentos: number;
            /** Folio */
            folio?: string | null;
            /** Web Id */
            web_id?: string | null;
            /** Fecha Ticket */
            fecha_ticket?: string | null;
            /** Hora Ticket */
            hora_ticket?: string | null;
            /** Total */
            total?: string | null;
            /** Subtotal */
            subtotal?: string | null;
            /** Iva */
            iva?: string | null;
            /** Sucursal */
            sucursal?: string | null;
            /** Caja */
            caja?: string | null;
            /** Rfc Emisor */
            rfc_emisor?: string | null;
            /** Confianza */
            confianza?: string | null;
            /** Error Code */
            error_code?: string | null;
            /** Error Msg */
            error_msg?: string | null;
            /** Image Key */
            image_key?: string | null;
            /** Cfdi Uuid */
            cfdi_uuid?: string | null;
            /** Correo Capturado En Portal */
            correo_capturado_en_portal?: string | null;
            /** Cfdi Disponible Hasta */
            cfdi_disponible_hasta?: string | null;
            /** Created At */
            created_at: string;
        };
        /** UpdateMemberRoleRequest */
        UpdateMemberRoleRequest: {
            rol: components["schemas"]["MembershipRole"];
        };
        /** UserTenantResponse */
        UserTenantResponse: {
            /** Id */
            id: string;
            /** Nombre */
            nombre: string;
            /** Slug */
            slug: string;
            /** Plan */
            plan: string;
            /** Rol */
            rol: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_with_google_v1_auth_google_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoogleAuthRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoogleAuthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_me_v1_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    list_user_tenants_v1_tenants_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantResponse"][];
                };
            };
        };
    };
    create_tenant_v1_tenants_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTenantRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_team_v1_team_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamMemberResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    invite_team_member_v1_team_invitations_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InviteMemberRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamMemberResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_member_role_v1_team__user_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string | null;
            };
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMemberRoleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamMemberResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tickets_v1_tickets_get: {
        parameters: {
            query?: {
                estado?: components["schemas"]["TicketEstado"] | null;
                merchant_id?: string | null;
                cursor?: string | null;
                limit?: number;
            };
            header?: {
                "X-Tenant-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedTicketsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_ticket_v1_tickets_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_ticket_v1_tickets_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ticket_v1_tickets__ticket_id__get: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string | null;
            };
            path: {
                ticket_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_ticket_v1_tickets__ticket_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string | null;
            };
            path: {
                ticket_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_ticket_events_v1_tickets__ticket_id__stream_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string | null;
            };
            path: {
                ticket_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_ticket_v1_tickets__ticket_id__retry_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string | null;
            };
            path: {
                ticket_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_cfdi_bundle_v1_tickets__ticket_id__cfdi_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Tenant-Id"?: string | null;
            };
            path: {
                ticket_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
